/**
 * ConsulTara TeleConsultation Platform - Extended Doctor Data
 * 
 * Comprehensive doctor profiles for all 10 departments with diverse
 * names, faces, locations in Metro Manila, and all required details.
 */

import type { DoctorProfile, DoctorReview, WeeklySchedule } from './types';

// ============================================================================
// Metro Manila Locations
// ============================================================================

const metroManilaLocations = [
  'Makati City',
  'Quezon City',
  'Manila',
  'Taguig City',
  'Pasig City',
  'Mandaluyong City',
  'San Juan City',
  'Parañaque City',
  'Pasay City',
  'Muntinlupa City',
  'Las Piñas City',
  'Marikina City',
  'Caloocan City',
  'Valenzuela City',
  'Malabon City',
  'Navotas City',
  'Pateros',
];

// ============================================================================
// Default Weekly Schedule
// ============================================================================

const defaultSchedule: WeeklySchedule = {
  monday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
      { startTime: '10:30', endTime: '11:00', isAvailable: true },
      { startTime: '11:00', endTime: '11:30', isAvailable: true },
      { startTime: '14:00', endTime: '14:30', isAvailable: true },
      { startTime: '14:30', endTime: '15:00', isAvailable: true },
      { startTime: '15:00', endTime: '15:30', isAvailable: true },
      { startTime: '15:30', endTime: '16:00', isAvailable: true },
    ]
  },
  tuesday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
      { startTime: '10:30', endTime: '11:00', isAvailable: true },
      { startTime: '14:00', endTime: '14:30', isAvailable: true },
      { startTime: '14:30', endTime: '15:00', isAvailable: true },
      { startTime: '15:00', endTime: '15:30', isAvailable: true },
    ]
  },
  wednesday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
      { startTime: '14:00', endTime: '14:30', isAvailable: true },
      { startTime: '14:30', endTime: '15:00', isAvailable: true },
    ]
  },
  thursday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
      { startTime: '10:30', endTime: '11:00', isAvailable: true },
      { startTime: '14:00', endTime: '14:30', isAvailable: true },
      { startTime: '14:30', endTime: '15:00', isAvailable: true },
      { startTime: '15:00', endTime: '15:30', isAvailable: true },
      { startTime: '15:30', endTime: '16:00', isAvailable: true },
    ]
  },
  friday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
      { startTime: '14:00', endTime: '14:30', isAvailable: true },
    ]
  },
  saturday: {
    isWorkingDay: true,
    slots: [
      { startTime: '09:00', endTime: '09:30', isAvailable: true },
      { startTime: '09:30', endTime: '10:00', isAvailable: true },
      { startTime: '10:00', endTime: '10:30', isAvailable: true },
    ]
  },
  sunday: {
    isWorkingDay: false,
    slots: []
  }
};

// ============================================================================
// Sample Reviews Generator
// ============================================================================

const reviewTemplates = [
  "Very professional and caring doctor. Highly recommended!",
  "Excellent consultation experience. The doctor was very thorough.",
  "Patient and understanding. Took time to explain everything clearly.",
  "Great bedside manner. Made me feel comfortable throughout.",
  "Very knowledgeable and experienced. I trust their expertise.",
  "Quick diagnosis and effective treatment. Very satisfied!",
  "Friendly staff and clean facility. Will definitely return.",
  "The doctor listened to all my concerns attentively.",
  "Professional service and reasonable consultation fee.",
  "Highly skilled doctor with excellent communication skills.",
];

function generateReviews(count: number): DoctorReview[] {
  const reviews: DoctorReview[] = [];
  for (let i = 0; i < count; i++) {
    reviews.push({
      id: `review-${Date.now()}-${i}`,
      rating: Math.floor(Math.random() * 2) + 4, // 4-5 stars
      comment: reviewTemplates[Math.floor(Math.random() * reviewTemplates.length)],
      date: new Date(Date.now() - Math.random() * 90 * 24 * 60 * 60 * 1000).toISOString(),
      isAnonymous: Math.random() > 0.5,
    });
  }
  return reviews;
}

// ============================================================================
// Professional Photo URLs (diverse faces)
// ============================================================================

const doctorPhotos = {
  male: [
    'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1580281657702-257584239a55?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1612531386530-97286d97c2d2?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1618498082410-b4aa22193b38?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1600878459138-e1123b37cb30?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=400&h=400&fit=crop&crop=face',
  ],
  female: [
    'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1651008376811-b90baee60c1f?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1614608682850-e0d6ed316d47?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1584820927498-cfe5211fd8bf?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1551836022-d5d88e9218df?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1607990281513-2c110a25bd8c?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1643297654416-05795d62e39c?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1559839914-17aae19cec71?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1623854767648-e7bb8009f0db?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1590611936760-eeb9bc598548?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=400&h=400&fit=crop&crop=face',
    'https://images.unsplash.com/photo-1558898479-33c0057a5d12?w=400&h=400&fit=crop&crop=face',
  ],
};

// ============================================================================
// Extended Doctor Data
// ============================================================================

export const extendedDoctors: DoctorProfile[] = [
  // ============================================================================
  // CARDIOLOGY DEPARTMENT (25 doctors)
  // ============================================================================
  {
    id: 'doc-card-001',
    userId: 'user-doc-card-001',
    firstName: 'Maria',
    lastName: 'Santos',
    email: 'maria.santos@consultara.ph',
    phone: '+63-917-123-4501',
    specialization: 'Interventional Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123456',
    yearsOfExperience: 18,
    education: 'MD from University of the Philippines Manila, Fellowship in Cardiology at Philippine Heart Center',
    bio: 'Dr. Maria Santos is a board-certified interventional cardiologist with expertise in coronary angioplasty and stent placement. She has performed over 3,000 cardiac procedures and is dedicated to preventive cardiology.',
    consultationFee: 1500,
    avatar: doctorPhotos.female[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Tagalog'],
    rating: 4.9,
    totalReviews: 342,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4501',
    reviews: generateReviews(5),
    createdAt: '2023-01-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-002',
    userId: 'user-doc-card-002',
    firstName: 'Jose',
    lastName: 'Reyes',
    email: 'jose.reyes@consultara.ph',
    phone: '+63-917-123-4502',
    specialization: 'Electrophysiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123457',
    yearsOfExperience: 15,
    education: 'MD from University of Santo Tomas, Cardiology Fellowship at St. Lukes Medical Center',
    bio: 'Dr. Jose Reyes specializes in heart rhythm disorders and cardiac electrophysiology. He is an expert in pacemaker implantation and ablation procedures for arrhythmias.',
    consultationFee: 1800,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 287,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4502',
    reviews: generateReviews(4),
    createdAt: '2023-02-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-003',
    userId: 'user-doc-card-003',
    firstName: 'Patricia',
    lastName: 'Garcia',
    email: 'patricia.garcia@consultara.ph',
    phone: '+63-917-123-4503',
    specialization: 'Heart Failure Management',
    department: 'cardiology',
    licenseNumber: 'PRC-0123458',
    yearsOfExperience: 20,
    education: 'MD from Ateneo School of Medicine, Fellowship at Philippine General Hospital',
    bio: 'Dr. Patricia Garcia is an expert in advanced heart failure management. She leads the heart failure program with a focus on innovative therapies and patient-centered care.',
    consultationFee: 2000,
    avatar: doctorPhotos.female[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Spanish'],
    rating: 4.9,
    totalReviews: 456,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4503',
    reviews: generateReviews(6),
    createdAt: '2022-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-004',
    userId: 'user-doc-card-004',
    firstName: 'Michael',
    lastName: 'Cruz',
    email: 'michael.cruz@consultara.ph',
    phone: '+63-917-123-4504',
    specialization: 'Pediatric Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123459',
    yearsOfExperience: 12,
    education: 'MD from De La Salle Health Sciences Institute, Pediatric Cardiology Fellowship at National Childrens Hospital',
    bio: 'Dr. Michael Cruz specializes in congenital heart defects and pediatric cardiac conditions. He provides compassionate care for children with heart problems.',
    consultationFee: 1600,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 198,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4504',
    reviews: generateReviews(3),
    createdAt: '2023-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-005',
    userId: 'user-doc-card-005',
    firstName: 'Angela',
    lastName: 'Mendoza',
    email: 'angela.mendoza@consultara.ph',
    phone: '+63-917-123-4505',
    specialization: 'Preventive Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123460',
    yearsOfExperience: 10,
    education: 'MD from Far Eastern University, Cardiology Training at Makati Medical Center',
    bio: 'Dr. Angela Mendoza focuses on cardiovascular disease prevention and risk factor management. She helps patients adopt heart-healthy lifestyles.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Mandarin'],
    rating: 4.8,
    totalReviews: 276,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4505',
    reviews: generateReviews(4),
    createdAt: '2022-11-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-006',
    userId: 'user-doc-card-006',
    firstName: 'Roberto',
    lastName: 'Tan',
    email: 'roberto.tan@consultara.ph',
    phone: '+63-917-123-4506',
    specialization: 'Echocardiography',
    department: 'cardiology',
    licenseNumber: 'PRC-0123461',
    yearsOfExperience: 14,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Roberto Tan is an expert in cardiac imaging and echocardiography. He provides detailed heart assessments using advanced ultrasound technology.',
    consultationFee: 1400,
    avatar: doctorPhotos.male[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Hokkien'],
    rating: 4.6,
    totalReviews: 189,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4506',
    reviews: generateReviews(3),
    createdAt: '2023-03-01T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-007',
    userId: 'user-doc-card-007',
    firstName: 'Catherine',
    lastName: 'Lim',
    email: 'catherine.lim@consultara.ph',
    phone: '+63-917-123-4507',
    specialization: 'Cardiac Rehabilitation',
    department: 'cardiology',
    licenseNumber: 'PRC-0123462',
    yearsOfExperience: 8,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Catherine Lim specializes in cardiac rehabilitation, helping patients recover after heart surgery and cardiac events through structured exercise programs.',
    consultationFee: 1100,
    avatar: doctorPhotos.female[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 156,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4507',
    reviews: generateReviews(3),
    createdAt: '2023-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-008',
    userId: 'user-doc-card-008',
    firstName: 'Eduardo',
    lastName: 'Villareal',
    email: 'eduardo.villareal@consultara.ph',
    phone: '+63-917-123-4508',
    specialization: 'Hypertension Management',
    department: 'cardiology',
    licenseNumber: 'PRC-0123463',
    yearsOfExperience: 16,
    education: 'MD from Manila Central University, Cardiology Fellowship at Philippine Heart Center',
    bio: 'Dr. Eduardo Villareal is an expert in hypertension management and cardiovascular risk assessment. He helps patients control blood pressure through lifestyle and medication.',
    consultationFee: 1300,
    avatar: doctorPhotos.male[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4508',
    reviews: generateReviews(4),
    createdAt: '2022-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-009',
    userId: 'user-doc-card-009',
    firstName: 'Rosario',
    lastName: 'Aquino',
    email: 'rosario.aquino@consultara.ph',
    phone: '+63-917-123-4509',
    specialization: 'Nuclear Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123464',
    yearsOfExperience: 11,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Rosario Aquino specializes in nuclear cardiology and cardiac imaging. She uses advanced nuclear medicine techniques to diagnose heart conditions.',
    consultationFee: 1700,
    avatar: doctorPhotos.female[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 298,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4509',
    reviews: generateReviews(5),
    createdAt: '2023-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-010',
    userId: 'user-doc-card-010',
    firstName: 'Fernando',
    lastName: 'Dela Cruz',
    email: 'fernando.delacruz@consultara.ph',
    phone: '+63-917-123-4510',
    specialization: 'Cardiac Surgery',
    department: 'cardiology',
    licenseNumber: 'PRC-0123465',
    yearsOfExperience: 22,
    education: 'MD from University of the Philippines Manila, Cardiac Surgery Fellowship at Cleveland Clinic',
    bio: 'Dr. Fernando Dela Cruz is a renowned cardiac surgeon with expertise in coronary bypass surgery and valve repair. He has performed over 5,000 successful surgeries.',
    consultationFee: 2500,
    avatar: doctorPhotos.male[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Spanish'],
    rating: 4.9,
    totalReviews: 512,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4510',
    reviews: generateReviews(6),
    createdAt: '2021-08-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-011',
    userId: 'user-doc-card-011',
    firstName: 'Beatriz',
    lastName: 'Gonzales',
    email: 'beatriz.gonzales@consultara.ph',
    phone: '+63-917-123-4511',
    specialization: 'Heart Valve Disease',
    department: 'cardiology',
    licenseNumber: 'PRC-0123466',
    yearsOfExperience: 13,
    education: 'MD from Cebu Institute of Medicine',
    bio: 'Dr. Beatriz Gonzales specializes in heart valve diseases and provides comprehensive care for patients with valvular heart conditions.',
    consultationFee: 1400,
    avatar: doctorPhotos.female[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.7,
    totalReviews: 201,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4511',
    reviews: generateReviews(3),
    createdAt: '2022-10-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-012',
    userId: 'user-doc-card-012',
    firstName: 'Ricardo',
    lastName: 'Bautista',
    email: 'ricardo.bautista@consultara.ph',
    phone: '+63-917-123-4512',
    specialization: 'Lipid Disorders',
    department: 'cardiology',
    licenseNumber: 'PRC-0123467',
    yearsOfExperience: 9,
    education: 'MD from Pamantasan ng Lungsod ng Maynila',
    bio: 'Dr. Ricardo Bautista focuses on cholesterol management and lipid disorders. He helps patients reduce cardiovascular risk through targeted therapy.',
    consultationFee: 1200,
    avatar: doctorPhotos.male[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 167,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4512',
    reviews: generateReviews(3),
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-013',
    userId: 'user-doc-card-013',
    firstName: 'Lourdes',
    lastName: 'Castillo',
    email: 'lourdes.castillo@consultara.ph',
    phone: '+63-917-123-4513',
    specialization: 'Vascular Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123468',
    yearsOfExperience: 17,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Lourdes Castillo specializes in peripheral vascular diseases and provides comprehensive care for patients with arterial and venous conditions.',
    consultationFee: 1600,
    avatar: doctorPhotos.female[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 278,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4513',
    reviews: generateReviews(4),
    createdAt: '2022-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-014',
    userId: 'user-doc-card-014',
    firstName: 'Antonio',
    lastName: 'Ramos',
    email: 'antonio.ramos@consultara.ph',
    phone: '+63-917-123-4514',
    specialization: 'Congestive Heart Failure',
    department: 'cardiology',
    licenseNumber: 'PRC-0123469',
    yearsOfExperience: 19,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Antonio Ramos is dedicated to treating congestive heart failure patients with the latest evidence-based therapies and personalized care plans.',
    consultationFee: 1800,
    avatar: doctorPhotos.male[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Kapampangan'],
    rating: 4.9,
    totalReviews: 345,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4514',
    reviews: generateReviews(5),
    createdAt: '2021-11-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-015',
    userId: 'user-doc-card-015',
    firstName: 'Margarita',
    lastName: 'Torres',
    email: 'margarita.torres@consultara.ph',
    phone: '+63-917-123-4515',
    specialization: 'Cardiac Imaging',
    department: 'cardiology',
    licenseNumber: 'PRC-0123470',
    yearsOfExperience: 7,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Margarita Torres uses advanced cardiac imaging techniques including CT angiography and cardiac MRI to provide accurate diagnoses.',
    consultationFee: 1300,
    avatar: doctorPhotos.female[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 134,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4515',
    reviews: generateReviews(2),
    createdAt: '2023-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-016',
    userId: 'user-doc-card-016',
    firstName: 'Ramon',
    lastName: 'Fernandez',
    email: 'ramon.fernandez@consultara.ph',
    phone: '+63-917-123-4516',
    specialization: 'Coronary Artery Disease',
    department: 'cardiology',
    licenseNumber: 'PRC-0123471',
    yearsOfExperience: 21,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Ramon Fernandez has extensive experience in managing coronary artery disease, from lifestyle modifications to complex interventions.',
    consultationFee: 2000,
    avatar: doctorPhotos.male[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 423,
    isAvailable: true,
    location: 'Manila',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4516',
    reviews: generateReviews(5),
    createdAt: '2020-06-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-017',
    userId: 'user-doc-card-017',
    firstName: 'Sofia',
    lastName: 'Navarro',
    email: 'sofia.navarro@consultara.ph',
    phone: '+63-917-123-4517',
    specialization: 'Women\'s Heart Health',
    department: 'cardiology',
    licenseNumber: 'PRC-0123472',
    yearsOfExperience: 12,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Sofia Navarro focuses on cardiovascular health in women, addressing gender-specific risk factors and heart conditions.',
    consultationFee: 1400,
    avatar: doctorPhotos.female[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Bicolano'],
    rating: 4.7,
    totalReviews: 198,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4517',
    reviews: generateReviews(3),
    createdAt: '2022-02-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-018',
    userId: 'user-doc-card-018',
    firstName: 'Carlos',
    lastName: 'Magno',
    email: 'carlos.magno@consultara.ph',
    phone: '+63-917-123-4518',
    specialization: 'Adult Congenital Heart Disease',
    department: 'cardiology',
    licenseNumber: 'PRC-0123473',
    yearsOfExperience: 15,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Carlos Magno specializes in caring for adults with congenital heart defects, providing long-term follow-up and management.',
    consultationFee: 1700,
    avatar: doctorPhotos.male[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 256,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4518',
    reviews: generateReviews(4),
    createdAt: '2022-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-019',
    userId: 'user-doc-card-019',
    firstName: 'Teresa',
    lastName: 'Villanueva',
    email: 'teresa.villanueva@consultara.ph',
    phone: '+63-917-123-4519',
    specialization: 'Sports Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123474',
    yearsOfExperience: 10,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Teresa Villanueva provides cardiac screening and care for athletes, helping them maintain optimal heart health during training and competition.',
    consultationFee: 1500,
    avatar: doctorPhotos.female[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 178,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4519',
    reviews: generateReviews(3),
    createdAt: '2023-03-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-020',
    userId: 'user-doc-card-020',
    firstName: 'Manuel',
    lastName: 'Ocampo',
    email: 'manuel.ocampo@consultara.ph',
    phone: '+63-917-123-4520',
    specialization: 'Cardiac Electrophysiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123475',
    yearsOfExperience: 14,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Manuel Ocampo is an expert in diagnosing and treating heart rhythm disorders using advanced electrophysiology techniques.',
    consultationFee: 1800,
    avatar: doctorPhotos.male[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Waray'],
    rating: 4.8,
    totalReviews: 267,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4520',
    reviews: generateReviews(4),
    createdAt: '2022-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-021',
    userId: 'user-doc-card-021',
    firstName: 'Corazon',
    lastName: 'Perez',
    email: 'corazon.perez@consultara.ph',
    phone: '+63-917-123-4521',
    specialization: 'Geriatric Cardiology',
    department: 'cardiology',
    licenseNumber: 'PRC-0123476',
    yearsOfExperience: 18,
    education: 'MD from Manila Central University',
    bio: 'Dr. Corazon Perez specializes in cardiovascular care for elderly patients, addressing age-related heart conditions with compassionate expertise.',
    consultationFee: 1400,
    avatar: doctorPhotos.female[10],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 312,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4521',
    reviews: generateReviews(5),
    createdAt: '2021-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-022',
    userId: 'user-doc-card-022',
    firstName: 'Luis',
    lastName: 'Aguilar',
    email: 'luis.aguilar@consultara.ph',
    phone: '+63-917-123-4522',
    specialization: 'Cardiac Catheterization',
    department: 'cardiology',
    licenseNumber: 'PRC-0123477',
    yearsOfExperience: 16,
    education: 'MD from Cebu Doctors University',
    bio: 'Dr. Luis Aguilar is highly skilled in cardiac catheterization procedures for diagnostic and therapeutic purposes.',
    consultationFee: 1900,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.7,
    totalReviews: 234,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4522',
    reviews: generateReviews(4),
    createdAt: '2022-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-023',
    userId: 'user-doc-card-023',
    firstName: 'Victoria',
    lastName: 'Domingo',
    email: 'victoria.domingo@consultara.ph',
    phone: '+63-917-123-4523',
    specialization: 'Cardiomyopathy',
    department: 'cardiology',
    licenseNumber: 'PRC-0123478',
    yearsOfExperience: 11,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Victoria Domingo specializes in cardiomyopathies and provides comprehensive management for patients with heart muscle diseases.',
    consultationFee: 1500,
    avatar: doctorPhotos.female[11],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 189,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8123-4523',
    reviews: generateReviews(3),
    createdAt: '2023-01-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-024',
    userId: 'user-doc-card-024',
    firstName: 'Francisco',
    lastName: 'Santiago',
    email: 'francisco.santiago@consultara.ph',
    phone: '+63-917-123-4524',
    specialization: 'Pulmonary Hypertension',
    department: 'cardiology',
    licenseNumber: 'PRC-0123479',
    yearsOfExperience: 13,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Francisco Santiago specializes in pulmonary hypertension and right heart conditions, offering advanced diagnostic and treatment options.',
    consultationFee: 1700,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.8,
    totalReviews: 245,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4524',
    reviews: generateReviews(4),
    createdAt: '2022-07-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-card-025',
    userId: 'user-doc-card-025',
    firstName: 'Esperanza',
    lastName: 'Luna',
    email: 'esperanza.luna@consultara.ph',
    phone: '+63-917-123-4525',
    specialization: 'Cardiovascular Prevention',
    department: 'cardiology',
    licenseNumber: 'PRC-0123480',
    yearsOfExperience: 9,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Esperanza Luna focuses on cardiovascular disease prevention through lifestyle counseling, risk assessment, and early intervention strategies.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[12],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 156,
    isAvailable: true,
    location: 'Caloocan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8123-4525',
    reviews: generateReviews(3),
    createdAt: '2023-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },

  // ============================================================================
  // DERMATOLOGY DEPARTMENT (25 doctors)
  // ============================================================================
  {
    id: 'doc-derm-001',
    userId: 'user-doc-derm-001',
    firstName: 'Isabella',
    lastName: 'Reyes',
    email: 'isabella.reyes@consultara.ph',
    phone: '+63-917-234-5601',
    specialization: 'Cosmetic Dermatology',
    department: 'dermatology',
    licenseNumber: 'PRC-0234501',
    yearsOfExperience: 12,
    education: 'MD from University of the Philippines Manila, Dermatology Residency at Philippine Dermatological Society',
    bio: 'Dr. Isabella Reyes combines medical dermatology with aesthetic treatments. She specializes in anti-aging procedures, laser treatments, and skin rejuvenation.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 398,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5601',
    reviews: generateReviews(5),
    createdAt: '2022-03-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-002',
    userId: 'user-doc-derm-002',
    firstName: 'Kenneth',
    lastName: 'Tan',
    email: 'kenneth.tan@consultara.ph',
    phone: '+63-917-234-5602',
    specialization: 'Pediatric Dermatology',
    department: 'dermatology',
    licenseNumber: 'PRC-0234502',
    yearsOfExperience: 14,
    education: 'MD from University of Santo Tomas, Pediatric Dermatology Fellowship',
    bio: 'Dr. Kenneth Tan specializes in skin conditions affecting children and adolescents, including eczema, birthmarks, and genetic skin disorders.',
    consultationFee: 1300,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Hokkien'],
    rating: 4.8,
    totalReviews: 287,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5602',
    reviews: generateReviews(4),
    createdAt: '2022-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-003',
    userId: 'user-doc-derm-003',
    firstName: 'Camille',
    lastName: 'Santos',
    email: 'camille.santos@consultara.ph',
    phone: '+63-917-234-5603',
    specialization: 'Dermatopathology',
    department: 'dermatology',
    licenseNumber: 'PRC-0234503',
    yearsOfExperience: 16,
    education: 'MD from Ateneo School of Medicine, Dermatopathology Fellowship',
    bio: 'Dr. Camille Santos is an expert in diagnosing skin diseases through microscopic examination. She specializes in skin cancer diagnosis and inflammatory conditions.',
    consultationFee: 1500,
    avatar: doctorPhotos.female[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 312,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5603',
    reviews: generateReviews(5),
    createdAt: '2021-09-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-004',
    userId: 'user-doc-derm-004',
    firstName: 'Gabriel',
    lastName: 'Cruz',
    email: 'gabriel.cruz@consultara.ph',
    phone: '+63-917-234-5604',
    specialization: 'Acne & Rosacea',
    department: 'dermatology',
    licenseNumber: 'PRC-0234504',
    yearsOfExperience: 8,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Gabriel Cruz specializes in treating acne, rosacea, and other facial skin conditions using the latest evidence-based treatments.',
    consultationFee: 1000,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 234,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5604',
    reviews: generateReviews(4),
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-005',
    userId: 'user-doc-derm-005',
    firstName: 'Monica',
    lastName: 'Garcia',
    email: 'monica.garcia@consultara.ph',
    phone: '+63-917-234-5605',
    specialization: 'Hair & Scalp Disorders',
    department: 'dermatology',
    licenseNumber: 'PRC-0234505',
    yearsOfExperience: 11,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Monica Garcia specializes in hair loss, alopecia, and scalp conditions. She provides comprehensive hair restoration treatments.',
    consultationFee: 1100,
    avatar: doctorPhotos.female[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Spanish'],
    rating: 4.6,
    totalReviews: 189,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5605',
    reviews: generateReviews(3),
    createdAt: '2022-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-006',
    userId: 'user-doc-derm-006',
    firstName: 'Adrian',
    lastName: 'Mendoza',
    email: 'adrian.mendoza@consultara.ph',
    phone: '+63-917-234-5606',
    specialization: 'Skin Cancer',
    department: 'dermatology',
    licenseNumber: 'PRC-0234506',
    yearsOfExperience: 15,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Adrian Mendoza is an expert in skin cancer detection and treatment, including Mohs surgery for precise removal of skin malignancies.',
    consultationFee: 1800,
    avatar: doctorPhotos.male[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 345,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5606',
    reviews: generateReviews(5),
    createdAt: '2021-11-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-007',
    userId: 'user-doc-derm-007',
    firstName: 'Jasmine',
    lastName: 'Villanueva',
    email: 'jasmine.villanueva@consultara.ph',
    phone: '+63-917-234-5607',
    specialization: 'Eczema & Psoriasis',
    department: 'dermatology',
    licenseNumber: 'PRC-0234507',
    yearsOfExperience: 10,
    education: 'MD from Manila Central University',
    bio: 'Dr. Jasmine Villanueva provides specialized care for chronic skin conditions like eczema and psoriasis using modern biologic therapies.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.7,
    totalReviews: 267,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5607',
    reviews: generateReviews(4),
    createdAt: '2022-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-008',
    userId: 'user-doc-derm-008',
    firstName: 'Daniel',
    lastName: 'Lim',
    email: 'daniel.lim@consultara.ph',
    phone: '+63-917-234-5608',
    specialization: 'Laser Dermatology',
    department: 'dermatology',
    licenseNumber: 'PRC-0234508',
    yearsOfExperience: 9,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Daniel Lim specializes in laser treatments for skin resurfacing, scar removal, and pigmentation correction.',
    consultationFee: 1400,
    avatar: doctorPhotos.male[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Mandarin'],
    rating: 4.8,
    totalReviews: 298,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5608',
    reviews: generateReviews(4),
    createdAt: '2022-10-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-009',
    userId: 'user-doc-derm-009',
    firstName: 'Angela',
    lastName: 'Torres',
    email: 'angela.torres@consultara.ph',
    phone: '+63-917-234-5609',
    specialization: 'Nail Disorders',
    department: 'dermatology',
    licenseNumber: 'PRC-0234509',
    yearsOfExperience: 7,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Angela Torres specializes in nail diseases and disorders, providing expert diagnosis and treatment for various nail conditions.',
    consultationFee: 900,
    avatar: doctorPhotos.female[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 156,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5609',
    reviews: generateReviews(3),
    createdAt: '2023-03-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-010',
    userId: 'user-doc-derm-010',
    firstName: 'Rafael',
    lastName: 'Bautista',
    email: 'rafael.bautista@consultara.ph',
    phone: '+63-917-234-5610',
    specialization: 'Contact Dermatitis',
    department: 'dermatology',
    licenseNumber: 'PRC-0234510',
    yearsOfExperience: 13,
    education: 'MD from Pamantasan ng Lungsod ng Maynila',
    bio: 'Dr. Rafael Bautista is an expert in allergic skin conditions, including contact dermatitis and patch testing for allergen identification.',
    consultationFee: 1100,
    avatar: doctorPhotos.male[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.6,
    totalReviews: 201,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5610',
    reviews: generateReviews(3),
    createdAt: '2022-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-011',
    userId: 'user-doc-derm-011',
    firstName: 'Patricia',
    lastName: 'Fernandez',
    email: 'patricia.fernandez@consultara.ph',
    phone: '+63-917-234-5611',
    specialization: 'Vitiligo Treatment',
    department: 'dermatology',
    licenseNumber: 'PRC-0234511',
    yearsOfExperience: 12,
    education: 'MD from Cebu Institute of Medicine',
    bio: 'Dr. Patricia Fernandez specializes in treating pigmentation disorders including vitiligo, using phototherapy and surgical techniques.',
    consultationFee: 1300,
    avatar: doctorPhotos.female[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5611',
    reviews: generateReviews(4),
    createdAt: '2022-02-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-012',
    userId: 'user-doc-derm-012',
    firstName: 'Marco',
    lastName: 'Aquino',
    email: 'marco.aquino@consultara.ph',
    phone: '+63-917-234-5612',
    specialization: 'Wound Care',
    department: 'dermatology',
    licenseNumber: 'PRC-0234512',
    yearsOfExperience: 11,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Marco Aquino specializes in chronic wound management, including diabetic ulcers and post-surgical wound care.',
    consultationFee: 1000,
    avatar: doctorPhotos.male[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 189,
    isAvailable: true,
    location: 'Caloocan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5612',
    reviews: generateReviews(3),
    createdAt: '2022-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-013',
    userId: 'user-doc-derm-013',
    firstName: 'Christine',
    lastName: 'Navarro',
    email: 'christine.navarro@consultara.ph',
    phone: '+63-917-234-5613',
    specialization: 'Injectable Fillers',
    department: 'dermatology',
    licenseNumber: 'PRC-0234513',
    yearsOfExperience: 8,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Christine Navarro is skilled in facial rejuvenation using dermal fillers and botulinum toxin for natural-looking results.',
    consultationFee: 1500,
    avatar: doctorPhotos.female[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 367,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5613',
    reviews: generateReviews(5),
    createdAt: '2022-07-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-014',
    userId: 'user-doc-derm-014',
    firstName: 'Vincent',
    lastName: 'Gonzales',
    email: 'vincent.gonzales@consultara.ph',
    phone: '+63-917-234-5614',
    specialization: 'Skin Infections',
    department: 'dermatology',
    licenseNumber: 'PRC-0234514',
    yearsOfExperience: 10,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Vincent Gonzales specializes in treating bacterial, viral, and fungal skin infections with targeted antimicrobial therapies.',
    consultationFee: 1000,
    avatar: doctorPhotos.male[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Bicolano'],
    rating: 4.6,
    totalReviews: 178,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5614',
    reviews: generateReviews(3),
    createdAt: '2022-09-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-015',
    userId: 'user-doc-derm-015',
    firstName: 'Samantha',
    lastName: 'Ramos',
    email: 'samantha.ramos@consultara.ph',
    phone: '+63-917-234-5615',
    specialization: 'Sun Damage Repair',
    department: 'dermatology',
    licenseNumber: 'PRC-0234515',
    yearsOfExperience: 9,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Samantha Ramos focuses on treating sun-damaged skin, including photoaging, sunspots, and pre-cancerous lesions.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 212,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5615',
    reviews: generateReviews(4),
    createdAt: '2022-11-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-016',
    userId: 'user-doc-derm-016',
    firstName: 'Jeremy',
    lastName: 'Castillo',
    email: 'jeremy.castillo@consultara.ph',
    phone: '+63-917-234-5616',
    specialization: 'Autoimmune Skin Diseases',
    department: 'dermatology',
    licenseNumber: 'PRC-0234516',
    yearsOfExperience: 14,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Jeremy Castillo specializes in autoimmune skin conditions like lupus, dermatomyositis, and scleroderma.',
    consultationFee: 1600,
    avatar: doctorPhotos.male[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 256,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5616',
    reviews: generateReviews(4),
    createdAt: '2021-08-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-017',
    userId: 'user-doc-derm-017',
    firstName: 'Bianca',
    lastName: 'Dela Cruz',
    email: 'bianca.delacruz@consultara.ph',
    phone: '+63-917-234-5617',
    specialization: 'Chemical Peels',
    department: 'dermatology',
    licenseNumber: 'PRC-0234517',
    yearsOfExperience: 7,
    education: 'MD from Manila Central University',
    bio: 'Dr. Bianca Dela Cruz offers various chemical peel treatments for skin rejuvenation, acne scarring, and pigmentation issues.',
    consultationFee: 1100,
    avatar: doctorPhotos.female[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 145,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5617',
    reviews: generateReviews(3),
    createdAt: '2023-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-018',
    userId: 'user-doc-derm-018',
    firstName: 'Christopher',
    lastName: 'Ocampo',
    email: 'christopher.ocampo@consultara.ph',
    phone: '+63-917-234-5618',
    specialization: 'Skin Allergy Testing',
    department: 'dermatology',
    licenseNumber: 'PRC-0234518',
    yearsOfExperience: 12,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Christopher Ocampo is an expert in identifying skin allergies through comprehensive testing and providing personalized treatment plans.',
    consultationFee: 1300,
    avatar: doctorPhotos.male[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Waray'],
    rating: 4.7,
    totalReviews: 198,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5618',
    reviews: generateReviews(3),
    createdAt: '2022-03-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-019',
    userId: 'user-doc-derm-019',
    firstName: 'Nicole',
    lastName: 'Perez',
    email: 'nicole.perez@consultara.ph',
    phone: '+63-917-234-5619',
    specialization: 'Teenage Skin Care',
    department: 'dermatology',
    licenseNumber: 'PRC-0234519',
    yearsOfExperience: 6,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Nicole Perez specializes in adolescent skin concerns including acne, oily skin, and proper skincare routines for teenagers.',
    consultationFee: 900,
    avatar: doctorPhotos.female[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 134,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5619',
    reviews: generateReviews(2),
    createdAt: '2023-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-020',
    userId: 'user-doc-derm-020',
    firstName: 'Emmanuel',
    lastName: 'Santiago',
    email: 'emmanuel.santiago@consultara.ph',
    phone: '+63-917-234-5620',
    specialization: 'Skin Tumors',
    department: 'dermatology',
    licenseNumber: 'PRC-0234520',
    yearsOfExperience: 17,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Emmanuel Santiago is experienced in diagnosing and treating both benign and malignant skin tumors with surgical precision.',
    consultationFee: 1700,
    avatar: doctorPhotos.male[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Kapampangan'],
    rating: 4.9,
    totalReviews: 345,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5620',
    reviews: generateReviews(5),
    createdAt: '2020-06-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-021',
    userId: 'user-doc-derm-021',
    firstName: 'Kathleen',
    lastName: 'Aguilar',
    email: 'kathleen.aguilar@consultara.ph',
    phone: '+63-917-234-5621',
    specialization: 'Melasma Treatment',
    department: 'dermatology',
    licenseNumber: 'PRC-0234521',
    yearsOfExperience: 10,
    education: 'MD from Cebu Doctors University',
    bio: 'Dr. Kathleen Aguilar specializes in treating melasma and other facial pigmentation issues with combination therapies for optimal results.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[10],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.7,
    totalReviews: 223,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5621',
    reviews: generateReviews(4),
    createdAt: '2022-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-022',
    userId: 'user-doc-derm-022',
    firstName: 'Martin',
    lastName: 'Luna',
    email: 'martin.luna@consultara.ph',
    phone: '+63-917-234-5622',
    specialization: 'Wart Removal',
    department: 'dermatology',
    licenseNumber: 'PRC-0234522',
    yearsOfExperience: 8,
    education: 'MD from Pamantasan ng Lungsod ng Maynila',
    bio: 'Dr. Martin Luna provides effective treatments for warts and viral skin growths using cryotherapy, laser, and topical medications.',
    consultationFee: 900,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 156,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5622',
    reviews: generateReviews(3),
    createdAt: '2023-02-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-023',
    userId: 'user-doc-derm-023',
    firstName: 'Clarisse',
    lastName: 'Domingo',
    email: 'clarisse.domingo@consultara.ph',
    phone: '+63-917-234-5623',
    specialization: 'Scar Treatment',
    department: 'dermatology',
    licenseNumber: 'PRC-0234523',
    yearsOfExperience: 11,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Clarisse Domingo specializes in scar revision using laser treatments, microneedling, and surgical techniques for improved appearance.',
    consultationFee: 1400,
    avatar: doctorPhotos.female[11],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 267,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5623',
    reviews: generateReviews(4),
    createdAt: '2022-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-024',
    userId: 'user-doc-derm-024',
    firstName: 'Ryan',
    lastName: 'Magno',
    email: 'ryan.magno@consultara.ph',
    phone: '+63-917-234-5624',
    specialization: 'Hidradenitis Suppurativa',
    department: 'dermatology',
    licenseNumber: 'PRC-0234524',
    yearsOfExperience: 13,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Ryan Magno specializes in treating hidradenitis suppurativa and other chronic inflammatory skin conditions.',
    consultationFee: 1300,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.7,
    totalReviews: 189,
    isAvailable: true,
    location: 'Caloocan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8234-5624',
    reviews: generateReviews(3),
    createdAt: '2022-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-derm-025',
    userId: 'user-doc-derm-025',
    firstName: 'Diana',
    lastName: 'Villanueva',
    email: 'diana.villanueva@consultara.ph',
    phone: '+63-917-234-5625',
    specialization: 'Skin Rejuvenation',
    department: 'dermatology',
    licenseNumber: 'PRC-0234525',
    yearsOfExperience: 9,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Diana Villanueva offers comprehensive skin rejuvenation treatments combining lasers, peels, and topical therapies for youthful skin.',
    consultationFee: 1200,
    avatar: doctorPhotos.female[12],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 178,
    isAvailable: true,
    location: 'Valenzuela City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8234-5625',
    reviews: generateReviews(3),
    createdAt: '2022-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },

  // ============================================================================
  // PEDIATRICS DEPARTMENT (25 doctors)
  // ============================================================================
  {
    id: 'doc-pedi-001',
    userId: 'user-doc-pedi-001',
    firstName: 'Elena',
    lastName: 'Santos',
    email: 'elena.santos@consultara.ph',
    phone: '+63-917-345-6701',
    specialization: 'General Pediatrics',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345601',
    yearsOfExperience: 20,
    education: 'MD from University of the Philippines Manila, Pediatrics Residency at Philippine General Hospital',
    bio: 'Dr. Elena Santos has dedicated her career to child health and development. She provides comprehensive care from newborns to adolescents with a gentle, compassionate approach.',
    consultationFee: 800,
    avatar: doctorPhotos.female[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Tagalog'],
    rating: 4.9,
    totalReviews: 567,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6701',
    reviews: generateReviews(6),
    createdAt: '2020-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-002',
    userId: 'user-doc-pedi-002',
    firstName: 'Benjamin',
    lastName: 'Cruz',
    email: 'benjamin.cruz@consultara.ph',
    phone: '+63-917-345-6702',
    specialization: 'Pediatric Infectious Diseases',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345602',
    yearsOfExperience: 15,
    education: 'MD from University of Santo Tomas, Infectious Disease Fellowship',
    bio: 'Dr. Benjamin Cruz specializes in diagnosing and treating infectious diseases in children. He is actively involved in vaccination programs and childhood immunization.',
    consultationFee: 900,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 345,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6702',
    reviews: generateReviews(5),
    createdAt: '2021-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-003',
    userId: 'user-doc-pedi-003',
    firstName: 'Grace',
    lastName: 'Reyes',
    email: 'grace.reyes@consultara.ph',
    phone: '+63-917-345-6703',
    specialization: 'Developmental Pediatrics',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345603',
    yearsOfExperience: 13,
    education: 'MD from Ateneo School of Medicine, Developmental Pediatrics Fellowship',
    bio: 'Dr. Grace Reyes focuses on children with developmental delays, autism spectrum disorders, and learning disabilities. She works closely with families to create individualized care plans.',
    consultationFee: 1000,
    avatar: doctorPhotos.female[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Spanish'],
    rating: 4.9,
    totalReviews: 423,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6703',
    reviews: generateReviews(5),
    createdAt: '2021-11-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-004',
    userId: 'user-doc-pedi-004',
    firstName: 'Jonathan',
    lastName: 'Garcia',
    email: 'jonathan.garcia@consultara.ph',
    phone: '+63-917-345-6704',
    specialization: 'Pediatric Pulmonology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345604',
    yearsOfExperience: 11,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Jonathan Garcia specializes in respiratory conditions in children including asthma, pneumonia, and chronic lung diseases.',
    consultationFee: 900,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 234,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6704',
    reviews: generateReviews(4),
    createdAt: '2022-02-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-005',
    userId: 'user-doc-pedi-005',
    firstName: 'Michelle',
    lastName: 'Tan',
    email: 'michelle.tan@consultara.ph',
    phone: '+63-917-345-6705',
    specialization: 'Pediatric Nutrition',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345605',
    yearsOfExperience: 9,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Michelle Tan focuses on childhood nutrition, growth monitoring, and dietary management for various pediatric conditions.',
    consultationFee: 800,
    avatar: doctorPhotos.female[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Hokkien'],
    rating: 4.6,
    totalReviews: 189,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8345-6705',
    reviews: generateReviews(3),
    createdAt: '2022-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-006',
    userId: 'user-doc-pedi-006',
    firstName: 'Patrick',
    lastName: 'Mendoza',
    email: 'patrick.mendoza@consultara.ph',
    phone: '+63-917-345-6706',
    specialization: 'Pediatric Gastroenterology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345606',
    yearsOfExperience: 14,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Patrick Mendoza specializes in digestive disorders in children, including food allergies, reflux, and inflammatory bowel disease.',
    consultationFee: 950,
    avatar: doctorPhotos.male[2],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 278,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6706',
    reviews: generateReviews(4),
    createdAt: '2021-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-007',
    userId: 'user-doc-pedi-007',
    firstName: 'Rachel',
    lastName: 'Lim',
    email: 'rachel.lim@consultara.ph',
    phone: '+63-917-345-6707',
    specialization: 'Pediatric Allergology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345607',
    yearsOfExperience: 10,
    education: 'MD from Manila Central University',
    bio: 'Dr. Rachel Lim specializes in childhood allergies, including food allergies, eczema, and allergic rhinitis. She provides comprehensive allergy testing and treatment.',
    consultationFee: 900,
    avatar: doctorPhotos.female[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Mandarin'],
    rating: 4.7,
    totalReviews: 234,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6707',
    reviews: generateReviews(4),
    createdAt: '2022-03-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-008',
    userId: 'user-doc-pedi-008',
    firstName: 'Steven',
    lastName: 'Villareal',
    email: 'steven.villareal@consultara.ph',
    phone: '+63-917-345-6708',
    specialization: 'Pediatric Neurology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345608',
    yearsOfExperience: 16,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Steven Villareal is an expert in neurological conditions affecting children, including epilepsy, headaches, and developmental delays.',
    consultationFee: 1100,
    avatar: doctorPhotos.male[3],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.9,
    totalReviews: 312,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6708',
    reviews: generateReviews(5),
    createdAt: '2020-11-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-009',
    userId: 'user-doc-pedi-009',
    firstName: 'Anna',
    lastName: 'Aquino',
    email: 'anna.aquino@consultara.ph',
    phone: '+63-917-345-6709',
    specialization: 'Neonatology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345609',
    yearsOfExperience: 18,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Anna Aquino specializes in caring for newborns, especially premature and critically ill infants. She has extensive NICU experience.',
    consultationFee: 1000,
    avatar: doctorPhotos.female[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 398,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6709',
    reviews: generateReviews(5),
    createdAt: '2019-06-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-010',
    userId: 'user-doc-pedi-010',
    firstName: 'Kevin',
    lastName: 'Dela Cruz',
    email: 'kevin.delacruz@consultara.ph',
    phone: '+63-917-345-6710',
    specialization: 'Pediatric Nephrology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345610',
    yearsOfExperience: 12,
    education: 'MD from Pamantasan ng Lungsod ng Maynila',
    bio: 'Dr. Kevin Dela Cruz specializes in kidney diseases in children, including urinary tract infections, kidney stones, and chronic kidney disease.',
    consultationFee: 950,
    avatar: doctorPhotos.male[4],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 201,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6710',
    reviews: generateReviews(4),
    createdAt: '2021-09-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-011',
    userId: 'user-doc-pedi-011',
    firstName: 'Laura',
    lastName: 'Gonzales',
    email: 'laura.gonzales@consultara.ph',
    phone: '+63-917-345-6711',
    specialization: 'Pediatric Endocrinology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345611',
    yearsOfExperience: 11,
    education: 'MD from Cebu Institute of Medicine',
    bio: 'Dr. Laura Gonzales treats hormonal disorders in children, including diabetes, thyroid conditions, and growth disorders.',
    consultationFee: 950,
    avatar: doctorPhotos.female[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6711',
    reviews: generateReviews(4),
    createdAt: '2021-10-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-012',
    userId: 'user-doc-pedi-012',
    firstName: 'Andrew',
    lastName: 'Bautista',
    email: 'andrew.bautista@consultara.ph',
    phone: '+63-917-345-6712',
    specialization: 'Pediatric Hematology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345612',
    yearsOfExperience: 14,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Andrew Bautista specializes in blood disorders in children, including anemia, bleeding disorders, and childhood leukemia.',
    consultationFee: 1000,
    avatar: doctorPhotos.male[5],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.8,
    totalReviews: 267,
    isAvailable: true,
    location: 'Caloocan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6712',
    reviews: generateReviews(4),
    createdAt: '2021-05-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-013',
    userId: 'user-doc-pedi-013',
    firstName: 'Vanessa',
    lastName: 'Torres',
    email: 'vanessa.torres@consultara.ph',
    phone: '+63-917-345-6713',
    specialization: 'Adolescent Medicine',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345613',
    yearsOfExperience: 8,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Vanessa Torres focuses on healthcare for teenagers, addressing physical, emotional, and social health concerns during adolescence.',
    consultationFee: 850,
    avatar: doctorPhotos.female[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 178,
    isAvailable: true,
    location: 'Makati City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8345-6713',
    reviews: generateReviews(3),
    createdAt: '2022-07-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-014',
    userId: 'user-doc-pedi-014',
    firstName: 'Mark',
    lastName: 'Ramos',
    email: 'mark.ramos@consultara.ph',
    phone: '+63-917-345-6714',
    specialization: 'Pediatric Emergency Medicine',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345614',
    yearsOfExperience: 12,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Mark Ramos is trained in emergency care for children, handling acute illnesses and injuries with expertise and calm.',
    consultationFee: 900,
    avatar: doctorPhotos.male[6],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Bicolano'],
    rating: 4.7,
    totalReviews: 223,
    isAvailable: true,
    location: 'Quezon City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6714',
    reviews: generateReviews(4),
    createdAt: '2021-12-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-015',
    userId: 'user-doc-pedi-015',
    firstName: 'Stephanie',
    lastName: 'Navarro',
    email: 'stephanie.navarro@consultara.ph',
    phone: '+63-917-345-6715',
    specialization: 'Pediatric Rheumatology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345615',
    yearsOfExperience: 10,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Stephanie Navarro treats autoimmune and inflammatory conditions in children, including juvenile arthritis and lupus.',
    consultationFee: 950,
    avatar: doctorPhotos.female[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 189,
    isAvailable: true,
    location: 'Taguig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6715',
    reviews: generateReviews(3),
    createdAt: '2022-04-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-016',
    userId: 'user-doc-pedi-016',
    firstName: 'Joseph',
    lastName: 'Fernandez',
    email: 'joseph.fernandez@consultara.ph',
    phone: '+63-917-345-6716',
    specialization: 'Pediatric Surgery',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345616',
    yearsOfExperience: 17,
    education: 'MD from University of the Philippines Manila',
    bio: 'Dr. Joseph Fernandez is a skilled pediatric surgeon handling congenital anomalies, hernias, and other surgical conditions in children.',
    consultationFee: 1200,
    avatar: doctorPhotos.male[7],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.9,
    totalReviews: 345,
    isAvailable: true,
    location: 'Pasig City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6716',
    reviews: generateReviews(5),
    createdAt: '2019-08-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-017',
    userId: 'user-doc-pedi-017',
    firstName: 'Angelica',
    lastName: 'Castillo',
    email: 'angelica.castillo@consultara.ph',
    phone: '+63-917-345-6717',
    specialization: 'Pediatric Oncology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345617',
    yearsOfExperience: 15,
    education: 'MD from Manila Central University',
    bio: 'Dr. Angelica Castillo provides compassionate care for children with cancer, working with families through diagnosis, treatment, and survivorship.',
    consultationFee: 1100,
    avatar: doctorPhotos.female[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Kapampangan'],
    rating: 4.9,
    totalReviews: 289,
    isAvailable: true,
    location: 'Mandaluyong City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6717',
    reviews: generateReviews(5),
    createdAt: '2020-03-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-018',
    userId: 'user-doc-pedi-018',
    firstName: 'Dennis',
    lastName: 'Ocampo',
    email: 'dennis.ocampo@consultara.ph',
    phone: '+63-917-345-6718',
    specialization: 'Pediatric Orthopedics',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345618',
    yearsOfExperience: 13,
    education: 'MD from St. Lukes College of Medicine',
    bio: 'Dr. Dennis Ocampo specializes in musculoskeletal conditions in children, including fractures, scoliosis, and hip disorders.',
    consultationFee: 1000,
    avatar: doctorPhotos.male[8],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Waray'],
    rating: 4.8,
    totalReviews: 234,
    isAvailable: true,
    location: 'San Juan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6718',
    reviews: generateReviews(4),
    createdAt: '2021-06-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-019',
    userId: 'user-doc-pedi-019',
    firstName: 'Jennifer',
    lastName: 'Perez',
    email: 'jennifer.perez@consultara.ph',
    phone: '+63-917-345-6719',
    specialization: 'Breastfeeding Medicine',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345619',
    yearsOfExperience: 8,
    education: 'MD from University of the East Ramon Magsaysay Memorial Medical Center',
    bio: 'Dr. Jennifer Perez supports mothers with breastfeeding challenges and provides guidance for optimal infant nutrition.',
    consultationFee: 800,
    avatar: doctorPhotos.female[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 167,
    isAvailable: true,
    location: 'Parañaque City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8345-6719',
    reviews: generateReviews(3),
    createdAt: '2022-09-05T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-020',
    userId: 'user-doc-pedi-020',
    firstName: 'Robert',
    lastName: 'Santiago',
    email: 'robert.santiago@consultara.ph',
    phone: '+63-917-345-6720',
    specialization: 'Pediatric Intensive Care',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345620',
    yearsOfExperience: 16,
    education: 'MD from Cebu Doctors University',
    bio: 'Dr. Robert Santiago is experienced in critical care for children, managing life-threatening conditions in the pediatric ICU.',
    consultationFee: 1100,
    avatar: doctorPhotos.male[9],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Cebuano'],
    rating: 4.9,
    totalReviews: 298,
    isAvailable: true,
    location: 'Pasay City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6720',
    reviews: generateReviews(5),
    createdAt: '2020-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-021',
    userId: 'user-doc-pedi-021',
    firstName: 'Melissa',
    lastName: 'Aguilar',
    email: 'melissa.aguilar@consultara.ph',
    phone: '+63-917-345-6721',
    specialization: 'Child Psychology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345621',
    yearsOfExperience: 11,
    education: 'MD from Pamantasan ng Lungsod ng Maynila',
    bio: 'Dr. Melissa Aguilar addresses behavioral and emotional concerns in children, working with families to promote mental wellness.',
    consultationFee: 900,
    avatar: doctorPhotos.female[10],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 212,
    isAvailable: true,
    location: 'Muntinlupa City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6721',
    reviews: generateReviews(4),
    createdAt: '2021-07-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-022',
    userId: 'user-doc-pedi-022',
    firstName: 'Philip',
    lastName: 'Luna',
    email: 'philip.luna@consultara.ph',
    phone: '+63-917-345-6722',
    specialization: 'Pediatric Dermatology',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345622',
    yearsOfExperience: 9,
    education: 'MD from Ateneo School of Medicine',
    bio: 'Dr. Philip Luna treats skin conditions in children and adolescents, including eczema, acne, and birthmarks.',
    consultationFee: 850,
    avatar: doctorPhotos.male[0],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.6,
    totalReviews: 178,
    isAvailable: true,
    location: 'Las Piñas City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8345-6722',
    reviews: generateReviews(3),
    createdAt: '2022-08-15T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-023',
    userId: 'user-doc-pedi-023',
    firstName: 'Katherine',
    lastName: 'Domingo',
    email: 'katherine.domingo@consultara.ph',
    phone: '+63-917-345-6723',
    specialization: 'Pediatric ENT',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345623',
    yearsOfExperience: 12,
    education: 'MD from De La Salle Health Sciences Institute',
    bio: 'Dr. Katherine Domingo specializes in ear, nose, and throat conditions in children, including ear infections, tonsillitis, and hearing issues.',
    consultationFee: 900,
    avatar: doctorPhotos.female[11],
    availability: defaultSchedule,
    languages: ['English', 'Filipino', 'Ilocano'],
    rating: 4.8,
    totalReviews: 245,
    isAvailable: true,
    location: 'Marikina City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6723',
    reviews: generateReviews(4),
    createdAt: '2021-03-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-024',
    userId: 'user-doc-pedi-024',
    firstName: 'Edward',
    lastName: 'Magno',
    email: 'edward.magno@consultara.ph',
    phone: '+63-917-345-6724',
    specialization: 'Pediatric Sports Medicine',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345624',
    yearsOfExperience: 10,
    education: 'MD from Far Eastern University',
    bio: 'Dr. Edward Magno cares for young athletes, treating sports injuries and providing guidance for safe physical activity in children.',
    consultationFee: 900,
    avatar: doctorPhotos.male[1],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.7,
    totalReviews: 198,
    isAvailable: true,
    location: 'Caloocan City',
    acceptsInsurance: true,
    contactNumber: '+63-2-8345-6724',
    reviews: generateReviews(3),
    createdAt: '2022-01-20T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
  {
    id: 'doc-pedi-025',
    userId: 'user-doc-pedi-025',
    firstName: 'Christina',
    lastName: 'Villanueva',
    email: 'christina.villanueva@consultara.ph',
    phone: '+63-917-345-6725',
    specialization: 'Pediatric Sleep Medicine',
    department: 'pediatrics',
    licenseNumber: 'PRC-0345625',
    yearsOfExperience: 7,
    education: 'MD from University of Santo Tomas',
    bio: 'Dr. Christina Villanueva helps children with sleep disorders, including sleep apnea, insomnia, and night terrors.',
    consultationFee: 850,
    avatar: doctorPhotos.female[12],
    availability: defaultSchedule,
    languages: ['English', 'Filipino'],
    rating: 4.5,
    totalReviews: 145,
    isAvailable: true,
    location: 'Valenzuela City',
    acceptsInsurance: false,
    contactNumber: '+63-2-8345-6725',
    reviews: generateReviews(2),
    createdAt: '2023-01-10T00:00:00Z',
    updatedAt: '2024-01-15T00:00:00Z'
  },
];

// Export default for easy import
export default extendedDoctors;
